name: Create CLI tools
on:
  push:
    branches:
      - main
    paths:
      - cli-tools-src/**/*
  workflow_dispatch:

concurrency:
  group: cli-tools
  cancel-in-progress: false

jobs:
  publish:
    name: Create CLI tools
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: |
          cd cli-tools-src
          go build -o cli-tools
          GOOS=windows go build -o cli-tools.exe
          mv cli-tools* ..
      - name: Git Commit/Push Changes
        uses: actions-x/commit@v6
        with:
          message: Built cli-tools
